# Generated by Django 4.1.5 on 2023-01-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stock_stockname_delete_stocksentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSentiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=200)),
                ('sentiment', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('session_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
