# Generated by Django 4.1.5 on 2023-01-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSentiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('stock_symbol', models.CharField(max_length=50)),
                ('sentiment', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('session_id', models.CharField(max_length=100)),
            ],
        ),
    ]
