# Generated by Django 4.0.5 on 2023-01-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stockcomment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockComment',
        ),
        migrations.DeleteModel(
            name='StockSentiment',
        ),
    ]
